### PR TITLE
add copy&paste menu

### PR DESCRIPTION
**Pull request by ryshi**
fix bug https://github.com/mayswind/AriaNg-Native/issues/2

### CODE REVIEW

**Comment by mayswind** [comment]
This code runs on Windows would also display a menu, and it does not support multi-language.

**Comment by ryshi** [comment]
there is no perfect solution for now, maybe this can be solved in next version of electron [https://github.com/christofferok/langly/issues/2](https://github.com/christofferok/langly/issues/2)

btw, this certainly can be done only on macOS, try new one.

**Comment by ryshi** [comment]
there is no perfect solution for now, maybe this can be solved in next version of electron [https://github.com/christofferok/langly/issues/2](https://github.com/christofferok/langly/issues/2)

btw, this certainly can be done only on macOS, try new one

**Comment by whhxp** [comment]
@ryshi I use your code on macOS 10.12.6, it works fine. Thanks a lot

**Comment by mayswind** [comment]
AriaNg Native has used a new method to solve this problem, so I close this pr.

**Pull request closed without merging**
